---
swagger: "2.0"
info:
  description: "Product Service"
  version: "2.0.0"
  title: "Swagger Product Service"

host: "25phk9rhx6.execute-api.eu-north-1.amazonaws.com"
basePath: "/dev"
tags:
  - name: "products"
    description: "Products API"
schemes:
  - "https"
paths:
  /products:
    post:
      tags:
        - "products"
      summary: "Create new product"
      description: "Create a new product"
      operationId: "createProduct"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Create a new product"
          required: true
          schema:
            $ref: "#/definitions/ProductInput"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Id"
        400:
          description: "Validationr error"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
    get:
      tags:
        - "products"
      summary: "Finds Products"
      description: "Finds available Products"
      operationId: "getProductsList"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"

  /products/{productId}:
    get:
      tags:
        - "products"
      summary: "Find Product by ID"
      description: "Returns a single product"
      operationId: "getProductsById"
      produces:
        - "application/json"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of product to return. UUID format"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Product"
        404:
          description: "Product not found"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  ProductInput:
    type: "object"
    required:
      - "title"
      - "description"
      - "price"
      - "count"
    properties:
      title:
        type: "string"
        example: "Product Title"
      description:
        type: "string"
        example: "Short Product Description"
      price:
        type: "integer"
        format: "int64"
        example: 10
      count:
        type: "integer"
        format: "int64"
        example: 2
  Product:
    type: "object"
    required:
      - "id"
      - "title"
      - "description"
      - "price"
      - "count"
    properties:
      id:
        type: "string"
        example: "03f42ea7-cf14-4ac4-a93b-66f3fdc60c69"
      title:
        type: "string"
        example: "Product Title"
      description:
        type: "string"
        example: "Short Product Description"
      price:
        type: "integer"
        format: "int64"
        example: 10
      count:
        type: "integer"
        format: "int64"
        example: 2
  Id:
    type: "object"
    required:
      - "id"
    properties:
      id:
        type: "string"
        example: "03f42ea7-cf14-4ac4-a93b-66f3fdc60c69"
  Error:
    type: "object"
    required:
      - "errorCode"
      - "message"
    properties:
      errorCode:
        type: "integer"
        format: "int32"
        example: 1000
      message:
        type: "string"
        example: "INTERNAL_SERVER_ERROR"
